# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

GOBIN = main
OUT = function.zip
PACKAGE = github.com/jgensler8/testfunction

GO_IMAGE=marcelocorreia/go-glide-builder
GO_IMAGE_TAG=0.0.24

FUNCTIONS = $(shell ls | sed -e 's/-pkg.go/.function/' | sed -e 's/-wrap.go/.function/' | sort | uniq )

all: ${FUNCTIONS}

%.function: %.go %.js %.zip
	echo done with $<

PKG_MOUNT=-v $$PWD/$*-pkg.go:/go/src/${PACKAGE}/$*-pkg.go
WRAP_MOUNT=-v $$PWD/$*-wrap.go:/go/src/${PACKAGE}/$*-wrap.go
GLIDE_MOUNT=-v $$PWD/glide.yaml:/go/src/${PACKAGE}/glide.yaml
MODEL_MOUNT=-v $$PWD/models:/go/src/${PACKAGE}/models

%.go: %.out
#	GOARCH="amd64" GOOS="linux" CGO_ENABLED=0 go build -tags node $(GOBIN).go
	docker run --rm --name builder -it ${PKG_MOUNT} ${WRAP_MOUNT} ${MODEL_MOUNT} ${GLIDE_MOUNT} -v /tmp/build:/tmp/build --workdir /go/src/${PACKAGE} ${GO_IMAGE}:${GO_IMAGE_TAG} sh -c "glide install && go build -o /tmp/build/${GOBIN}"
	mv /tmp/build/${GOBIN} output/fx/$*/${GOBIN}

# not sure why we need to run install before zipping. Might as well let GCF install our dependency
%.js: %.out
	docker run --rm --name builder -it -v $$PWD:/workdir --workdir /workdir node:8 npm install --ignore-scripts --save local_modules/execer
	cp -r node_modules output/fx/$*/node_modules
	cp index.js output/fx/$*/index.js
	cp package.json output/fx/$*/package.json

%.out:
	mkdir -p output/fx/$*

%.zip:
	cd output/fx/$* && zip -FS -r $(OUT) main node_modules index.js package.json -x *build*
