# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PACKAGE = {{apiPackage}}

GO_IMAGE=marcelocorreia/go-glide-builder
GO_IMAGE_TAG=0.0.24

BUILD_IMAGE=jgensl2/go-fxgen-builder
BUILD_IMAGE_TAG=v4.0.0

FUNCTIONS = $(shell ls | sed -e 's/-pkg.go/.function/' | sed -e 's/-wrap.go/.function/' | sort | uniq )

all: package ${FUNCTIONS}

%.function: %.build
	echo done with $<

package:
	docker run -it --rm -v $$PWD:/workdir --workdir=/workdir ${GO_IMAGE}:${GO_IMAGE_TAG} glide install

%.build:
	docker run -it --rm -e PACKAGE=${PACKAGE} -e FUNCTION=$* -v $$PWD:/workdir -v $$PWD/output:/output ${BUILD_IMAGE}:${BUILD_IMAGE_TAG}
